import { NextResponse } from 'next/server';
import db from '@/lib/db';

export const DEFAULT_EMAIL_TEMPLATES: Record<string, any> = {
  order_confirmation: {
    id: 'order_confirmation',
    nameTr: 'Sipariş Onayı & Kavrum Kuyruğu',
    nameEn: 'Order Confirmation & Roast Queued',
    name: 'Order Confirmation & Roast Queued',
    badgeTr: 'KAVURMAHANE SİPARİŞ ONAYI',
    badgeEn: 'ROASTERY ORDER CONFIRMATION',
    badge: 'ROASTERY ORDER CONFIRMATION',
    subjectTr: 'Partiniz Kavrum İçin Sıraya Alındı ☕ [Sipariş #{{order_id}}]',
    subjectEn: 'Batch Scheduled for Roast ☕ [Order #{{order_id}}]',
    subject: 'Batch Scheduled for Roast ☕ [Order #{{order_id}}]',
    preheaderTr: 'Nitelikli kahveniz İstanbul atölyemizde taze kavrum için sıraya alındı.',
    preheaderEn: 'Your specialty coffee has been queued for small-batch roasting in İstanbul.',
    preheader: 'Your specialty coffee has been queued for small-batch roasting in İstanbul.',
    heroImage: '/images/hero_roast_order.png',
    headlineTr: 'Çekirdekleriniz Kavurma İçin Sıraya Alındı',
    headlineEn: 'Your Beans Are Scheduled For Roasting',
    headline: 'Your Beans Are Scheduled For Roasting',
    subtitleTr: 'Mikro Parti Nitelikli Kavrum #{{order_id}}',
    subtitleEn: 'Micro-Batch Specialty Roast Lot #{{order_id}}',
    subtitle: 'Micro-Batch Specialty Roast Lot #{{order_id}}',
    bodyTr: 'Coffee Esto’yu tercih ettiğiniz için teşekkür ederiz, {{customer_name}}. Baş kavurucumuz, siparişinizdeki single-origin çekirdekleri tamburlu kavurma için sıraya aldı. Çiçeksi ve meyvemsi aromaları korumak adına her paket, tek yönlü gaz tahliye valfli kilitli ambalajında mühürlenir.',
    bodyEn: 'Thank you for choosing Coffee Esto, {{customer_name}}. Our roastmaster has queued your single-origin lots for precision drum roasting. Every pouch is heat-sealed immediately with a one-way degassing valve to protect volatile floral aromatics and fruit sweetness.',
    body: 'Thank you for choosing Coffee Esto, {{customer_name}}. Our roastmaster has queued your single-origin lots for precision drum roasting. Every pouch is heat-sealed immediately with a one-way degassing valve to protect volatile floral aromatics and fruit sweetness.',
    roastmasterNoteTr: 'Kavurucu Notu: V60 veya Chemex filtre demlemelerinde en berrak tat profili için çekirdeklerinizi kavrum tarihinden itibaren 7 gün dinlendirmenizi öneririz.',
    roastmasterNoteEn: 'Roaster’s Tip: For pour-over brewing (V60/Chemex), allow beans to rest 7 days post-roast for optimal extraction and clarity.',
    roastmasterNote: 'Roaster’s Tip: For pour-over brewing (V60/Chemex), allow beans to rest 7 days post-roast for optimal extraction and clarity.',
    buttonTextTr: 'Kavrum ve Sipariş Durumunu Takip Et',
    buttonTextEn: 'Track Roast & Order Status',
    buttonText: 'Track Roast & Order Status',
    buttonUrl: '{{tracking_url}}',
    secondaryButtonTextTr: 'Demleme Rehberlerini İncele',
    secondaryButtonTextEn: 'Browse Brew Guides',
    secondaryButtonText: 'Browse Brew Guides',
    secondaryButtonUrl: 'https://coffeeesto.com/blog',
    footerNoteTr: 'Coffee Esto Roastery • Karaköy, İstanbul • Doğrudan Ticaret Nitelikli Çekirdekler',
    footerNoteEn: 'Coffee Esto Roastery • Karaköy, İstanbul • Direct Trade Single Origins',
    footerNote: 'Coffee Esto Roastery • Karaköy, İstanbul • Direct Trade Single Origins',
    enabled: true,
  },
  order_shipped: {
    id: 'order_shipped',
    nameTr: 'Sipariş Kargoya Verildi & Takip',
    nameEn: 'Order Dispatched & Courier Tracking',
    name: 'Order Dispatched & Courier Tracking',
    badgeTr: 'SEVKİYAT VE KARGO BİLDİRİMİ',
    badgeEn: 'DISPATCH & COURIER NOTICE',
    badge: 'DISPATCH & COURIER NOTICE',
    subjectTr: 'Taze Kavruldu ve Yola Çıktı! 📦 [Sipariş #{{order_id}}]',
    subjectEn: 'Freshly Roasted & On Its Way! 📦 [Order #{{order_id}}]',
    subject: 'Freshly Roasted & On Its Way! 📦 [Order #{{order_id}}]',
    preheaderTr: 'Kahveniz {{carrier_name}} ile yola çıktı. Takip No: {{tracking_number}}',
    preheaderEn: 'Your coffee is on the road with {{carrier_name}}. Tracking: {{tracking_number}}',
    preheader: 'Your coffee is on the road with {{carrier_name}}. Tracking: {{tracking_number}}',
    heroImage: '/images/brand-carrier.webp',
    headlineTr: 'Taze Kavrum Kahveniz Atölyeden Çıktı',
    headlineEn: 'Your Fresh Roast Has Departed The Atelier',
    headline: 'Your Fresh Roast Has Departed The Atelier',
    subtitleTr: 'Kargo Takip No: {{tracking_number}} ({{carrier_name}})',
    subtitleEn: 'Courier Reference: {{tracking_number}} ({{carrier_name}})',
    subtitle: 'Courier Reference: {{tracking_number}} ({{carrier_name}})',
    bodyTr: 'Harika haber {{customer_name}}! Yeni mühürlenmiş taze kahve paketleriniz İstanbul kavurmahanemizden yola çıktı. {{carrier_name}} güvencesiyle kapınıza doğru ulaşıyor.',
    bodyEn: 'Great news, {{customer_name}}! Your freshly sealed coffee pouches have departed our Istanbul roastery. They are currently in transit with {{carrier_name}} and heading directly to your doorstep.',
    body: 'Great news, {{customer_name}}! Your freshly sealed coffee pouches have departed our Istanbul roastery. They are currently in transit with {{carrier_name}} and heading directly to your doorstep.',
    roastmasterNoteTr: 'Gaz Salınım Bildirimi: Çekirdekleriniz {{roast_date}} tarihinde kavruldu. Paketiniz ulaştığında en lezzetli içim penceresine giriş yapacaktır.',
    roastmasterNoteEn: 'Degassing Alert: Your beans were roasted on {{roast_date}}. They will enter their peak flavor window right as your package arrives.',
    roastmasterNote: 'Degassing Alert: Your beans were roasted on {{roast_date}}. They will enter their peak flavor window right as your package arrives.',
    buttonTextTr: 'Kargo Teslimatını Takip Et',
    buttonTextEn: 'Track Courier Delivery',
    buttonText: 'Track Courier Delivery',
    buttonUrl: '{{tracking_url}}',
    secondaryButtonTextTr: 'Barista Demleme Reçeteleri',
    secondaryButtonTextEn: 'View Barista Brew Recipes',
    secondaryButtonText: 'View Barista Brew Recipes',
    secondaryButtonUrl: 'https://coffeeesto.com/blog',
    footerNoteTr: 'Öğütüm boyutu veya demleme hakkında sorularınız mı var? Bu e-postayı yanıtlayabilirsiniz.',
    footerNoteEn: 'Questions about your grind size or extraction? Reply directly to this email.',
    footerNote: 'Questions about your grind size or extraction? Reply directly to this email.',
    enabled: true,
  },
  review_request: {
    id: 'review_request',
    nameTr: '7. Gün Tadım Deneyimi & Yorum',
    nameEn: '7-Day Post-Delivery Review Request',
    name: '7-Day Post-Delivery Review Request',
    badgeTr: 'TADIM VE DEGÜSTASYON DEĞERLENDİRMESİ',
    badgeEn: 'CUPPING & TASTING REVIEW',
    badge: 'CUPPING & TASTING REVIEW',
    subjectTr: 'Kahvenizin tadı nasıl gidiyor, {{customer_name}}? ☕ Notlarınızı paylaşın',
    subjectEn: 'How is your cup tasting, {{customer_name}}? ☕ Share your notes',
    subject: 'How is your cup tasting, {{customer_name}}? ☕ Share your notes',
    preheaderTr: 'Geri bildiriminiz kavurucularımızın her hasat partisini kalibre etmesini sağlar. 1 tıkla puanlayın.',
    preheaderEn: 'Your feedback helps our roasters calibrate each harvest lot. Review in 1 click.',
    preheader: 'Your feedback helps our roasters calibrate each harvest lot. Review in 1 click.',
    heroImage: '/images/barista-chemex.webp',
    headlineTr: 'Kahvenizin Demleme Performansı Nasıl Oldu?',
    headlineEn: 'How Did Your Roast Brew?',
    headline: 'How Did Your Roast Brew?',
    subtitleTr: 'Kavurmahane Ekibimiz İçin Doğrudan Geri Bildirim',
    subtitleEn: 'Direct Feedback For Our Roastery Team',
    subtitle: 'Direct Feedback For Our Roastery Team',
    bodyTr: 'Merhaba {{customer_name}}, {{last_product_name}} kahveniz artık ideal gaz salınım süresini tamamladı. Fincanınızdaki yasemin, narenciye veya çikolata notaları nasıl çıktı? Tadım deneyiminizi topluluğumuzla paylaşarak diğer kahveseverlere rehberlik edin.',
    bodyEn: 'Hi {{customer_name}}, your {{last_product_name}} has now rested to its optimal degassing window. Did the jasmine, bergamot, or cocoa notes shine through in your cup? Share your tasting review with our roastery atelier to help other coffee lovers discover exceptional brews.',
    body: 'Hi {{customer_name}}, your {{last_product_name}} has now rested to its optimal degassing window. Did the jasmine, bergamot, or cocoa notes shine through in your cup? Share your tasting review with our roastery atelier to help other coffee lovers discover exceptional brews.',
    roastmasterNoteTr: 'Tadım İpucu: Ekstraksiyon hafif keskin veya acı hissedilirse, öğütümünüzü 1 kademe kalınlaştırın veya su sıcaklığını 92°C’ye düşürün.',
    roastmasterNoteEn: 'Cupping Tip: If extraction tastes slightly sharp, coarsen your grind 1 notch or drop brew water temperature to 92°C.',
    roastmasterNote: 'Cupping Tip: If extraction tastes slightly sharp, coarsen your grind 1 notch or drop brew water temperature to 92°C.',
    buttonTextTr: '1 Tıkla Değerlendir & Yorum Yaz',
    buttonTextEn: 'Leave a 1-Click Review',
    buttonText: 'Leave a 1-Click Review',
    buttonUrl: 'https://coffeeesto.com/coffee',
    secondaryButtonTextTr: 'Demleme Rehberlerini Keşfet',
    secondaryButtonTextEn: 'Explore Brew Guides',
    secondaryButtonText: 'Explore Brew Guides',
    secondaryButtonUrl: 'https://coffeeesto.com/blog',
    footerNoteTr: 'İstanbul’da siparişe özel küçük partilerle kavruldu • Coffee Esto Roastery',
    footerNoteEn: 'Roasted to order in small batches in İstanbul • Coffee Esto Roastery',
    footerNote: 'Roasted to order in small batches in İstanbul • Coffee Esto Roastery',
    enabled: true,
  },
  refill_reminder: {
    id: 'refill_reminder',
    nameTr: '21. Gün Tazelik & Yenileme Uyarısı',
    nameEn: '21-Day Peak Flavor Refill Alert',
    name: '21-Day Peak Flavor Refill Alert',
    badgeTr: '21 GÜNLÜK TAZELİK PENCERESİ',
    badgeEn: '21-DAY FRESHNESS ALERT',
    badge: '21-DAY FRESHNESS ALERT',
    subjectTr: 'Taze bir kavrum zamanı mı? ☕ Sonraki paketinizde %10 indirim',
    subjectEn: 'Time for a fresh roast? ☕ Enjoy 10% off your next batch',
    subject: 'Time for a fresh roast? ☕ Enjoy 10% off your next batch',
    preheaderTr: 'Son siparişinizden bu yana 3 hafta geçti. Sabah fincanınızı zirve aromalarda tutun.',
    preheaderEn: 'It has been 3 weeks since your last order. Keep your morning cup at peak aromatics.',
    preheader: 'It has been 3 weeks since your last order. Keep your morning cup at peak aromatics.',
    heroImage: '/images/brand-beans.webp',
    headlineTr: 'Sabah Fincanınızı Zirve Aromalarda Tutun',
    headlineEn: 'Keep Your Morning Cup At Peak Aromatics',
    headline: 'Keep Your Morning Cup At Peak Aromatics',
    subtitleTr: 'Nitelikli Kavrumlar 7–28. Günler Arasında En Canlıdır',
    subtitleEn: 'Specialty Roasts Are Most Vibrant In Days 7–28',
    subtitle: 'Specialty Roasts Are Most Vibrant In Days 7–28',
    bodyTr: 'Merhaba {{customer_name}}, {{last_product_name}} kahvenizi sipariş etmenizin üzerinden yaklaşık 21 gün geçti. Çekirdekler 4 haftayı aştıkça narin yasemin, şeftali ve narenciye yağları kademeli olarak azalır. Taze hasat kahvelerimizi yeniden sipariş edin, VIP indiriminin tadını çıkarın.',
    bodyEn: 'Hi {{customer_name}}, it has been roughly 21 days since your last batch of {{last_product_name}}. As whole bean coffee ages beyond 4 weeks, delicate jasmine, peach, and citrus notes gradually dissipate. Reorder fresh lots today and enjoy a VIP replenishment discount.',
    body: 'Hi {{customer_name}}, it has been roughly 21 days since your last batch of {{last_product_name}}. As whole bean coffee ages beyond 4 weeks, delicate jasmine, peach, and citrus notes gradually dissipate. Reorder fresh lots today and enjoy a VIP replenishment discount.',
    roastmasterNoteTr: 'VIP Avantajı: Tüm single origin ve espresso harmanlarında %10 özel indirim için ödeme adımında REFILL10 kodunu kullanın.',
    roastmasterNoteEn: 'VIP Perk: Use secret code REFILL10 at checkout for an exclusive 10% discount on all single origins and espresso blends.',
    roastmasterNote: 'VIP Perk: Use secret code REFILL10 at checkout for an exclusive 10% discount on all single origins and espresso blends.',
    buttonTextTr: 'Taze Kavrum Siparişi Ver (%10 İndirim)',
    buttonTextEn: 'Order Fresh Roasts (10% Off)',
    buttonText: 'Order Fresh Roasts (10% Off)',
    buttonUrl: 'https://coffeeesto.com/coffee?coupon=REFILL10',
    secondaryButtonTextTr: 'Yeni Hasatları Keşfet',
    secondaryButtonTextEn: 'Explore New Harvests',
    secondaryButtonText: 'Explore New Harvests',
    secondaryButtonUrl: 'https://coffeeesto.com/coffee',
    footerNoteTr: 'İstanbul’da siparişe özel kavrulan doğrudan ticaret mikro lotlar.',
    footerNoteEn: 'Ethically sourced microlots roasted to order in Istanbul.',
    footerNote: 'Ethically sourced microlots roasted to order in Istanbul.',
    enabled: true,
  },
  abandoned_cart: {
    id: 'abandoned_cart',
    nameTr: 'Sepet Hatırlatma & 24 Saatlik Rezerv',
    nameEn: 'Abandoned Cart & Reserve Hold',
    name: 'Abandoned Cart & Reserve Hold',
    badgeTr: 'REZERVE KAHVE PARTİSİ • 24 SAAT',
    badgeEn: 'RESERVED COFFEE BATCH • 24H HOLD',
    badge: 'RESERVED COFFEE BATCH • 24H HOLD',
    subjectTr: 'Çekirdeklerinizi haznede mi unuttunuz, {{customer_name}}? ☕',
    subjectEn: 'Did you leave your beans in the hopper, {{customer_name}}?',
    subject: 'Did you leave your beans in the hopper, {{customer_name}}?',
    preheaderTr: 'Seçtiğiniz nitelikli kahveler rezervde tutuluyor. Siparişinizi tamamlayın.',
    preheaderEn: 'Your specialty coffee selection is held in reserve. Complete your order today.',
    preheader: 'Your specialty coffee selection is held in reserve. Complete your order today.',
    heroImage: '/images/coffee_grouped.png',
    headlineTr: 'Özel Çekirdekleriniz Haznede Sizi Bekliyor',
    headlineEn: 'Your Artisan Coffee Is Waiting In The Hopper',
    headline: 'Your Artisan Coffee Is Waiting In The Hopper',
    subtitleTr: 'Sınırlı Mevsimsel Mikro Lotlar Hızla Tükeniyor',
    subtitleEn: 'Limited Seasonal Micro-Lots Sell Out Rapidly',
    subtitle: 'Limited Seasonal Micro-Lots Sell Out Rapidly',
    bodyTr: 'Sepetinizde seçkin kahveler bıraktığınızı fark ettik, {{customer_name}}. Seçtiğiniz paketler için 24 saatlik geçici bir rezerv oluşturduk. Bu hasat partisi tükenmeden sepetinizi tamamlayın.',
    bodyEn: 'We noticed you left some extraordinary coffees in your cart, {{customer_name}}. We have placed a temporary 24-hour reserve on your bag selection. Complete your checkout today to secure your batch before this harvest lot is fully allocated.',
    body: 'We noticed you left some extraordinary coffees in your cart, {{customer_name}}. We have placed a temporary 24-hour reserve on your bag selection. Complete your checkout today to secure your batch before this harvest lot is fully allocated.',
    roastmasterNoteTr: 'Çiğ çekirdeklerimiz Etiyopya, Kolombiya ve Guatemala’daki küçük ölçekli aile çiftlikleriyle doğrudan ticaret yoluyla tedarik edilmektedir.',
    roastmasterNoteEn: 'Our green coffees are sourced through direct-trade relationships with smallholder family farms in Ethiopia, Colombia, and Guatemala.',
    roastmasterNote: 'Our green coffees are sourced through direct-trade relationships with smallholder family farms in Ethiopia, Colombia, and Guatemala.',
    buttonTextTr: 'Rezerve Çekirdeklerini Güvenceye Al',
    buttonTextEn: 'Secure Your Reserved Beans',
    buttonText: 'Secure Your Reserved Beans',
    buttonUrl: 'https://coffeeesto.com/checkout',
    secondaryButtonTextTr: 'Tadım Profillerini İncele',
    secondaryButtonTextEn: 'View Tasting Profiles',
    secondaryButtonText: 'View Tasting Profiles',
    secondaryButtonUrl: 'https://coffeeesto.com/coffee',
    footerNoteTr: 'İstanbul’da siparişe özel kavrulan nitelikli doğrudan ticaret kahveleri.',
    footerNoteEn: 'Direct-trade specialty coffees roasted to order in İstanbul.',
    footerNote: 'Direct-trade specialty coffees roasted to order in İstanbul.',
    enabled: true,
  },
  welcome_series: {
    id: 'welcome_series',
    nameTr: 'Kavurmahaneye Hoş Geldiniz & Karşılama',
    nameEn: 'Welcome to the Atelier & Onboarding',
    name: 'Welcome to the Atelier & Onboarding',
    badgeTr: 'KAVURMAHANE ATÖLYESİNE HOŞ GELDİNİZ',
    badgeEn: 'WELCOME TO THE ROASTERY ATELIER',
    badge: 'WELCOME TO THE ROASTERY ATELIER',
    subjectTr: 'Coffee Esto’ya Hoş Geldiniz ☕ %10 Üye İndiriminiz Hazır',
    subjectEn: 'Welcome to Coffee Esto ☕ Your 10% Member Perk Awaits',
    subject: 'Welcome to Coffee Esto ☕ Your 10% Member Perk Awaits',
    preheaderTr: 'İstanbul’da siparişe özel kavrulan doğrudan ticaret kahveler. WELCOME10 kodunu kullanın.',
    preheaderEn: 'Direct-trade single-origins roasted to order in Istanbul. Enjoy code WELCOME10.',
    preheader: 'Direct-trade single-origins roasted to order in Istanbul. Enjoy code WELCOME10.',
    heroImage: '/images/barista-class.webp',
    headlineTr: 'Siparişe Özel Kavrulan Nitelikli Kahveler',
    headlineEn: 'Exceptional Coffee, Roasted To Order',
    headline: 'Exceptional Coffee, Roasted To Order',
    subtitleTr: 'Doğrudan Ticaret Tek Köken Çekirdekler & İmza Harmanlar',
    subtitleEn: 'Direct Trade Single Origins & Signature Blends',
    subtitle: 'Direct Trade Single Origins & Signature Blends',
    bodyTr: 'Coffee Esto topluluğuna hoş geldiniz, {{customer_name}}. Etiyopya, Kolombiya ve Guatemala’daki partner çiftliklerimizden doğrudan ticaretle çekirdek tedarik ediyoruz. Her kahve İstanbul atölyemizde siparişe özel kavrulur ve tek yönlü valfli ambalajlarda tazece mühürlenir.',
    bodyEn: 'Welcome to the Coffee Esto community, {{customer_name}}. We source transparent single-origin coffees directly from partner farms across Ethiopia, Colombia, and Guatemala. Every bean is small-batch drum roasted in our Istanbul atelier and sealed fresh with one-way degassing valves.',
    body: 'Welcome to the Coffee Esto community, {{customer_name}}. We source transparent single-origin coffees directly from partner farms across Ethiopia, Colombia, and Guatemala. Every bean is small-batch drum roasted in our Istanbul atelier and sealed fresh with one-way degassing valves.',
    roastmasterNoteTr: 'İlk Sipariş Avantajı: İlk kahve siparişinizde %10 indirim kazanmak için ödeme adımında WELCOME10 kodunu kullanın.',
    roastmasterNoteEn: 'First Order Perk: Enjoy 10% off your first coffee order with code WELCOME10 at checkout.',
    roastmasterNote: 'First Order Perk: Enjoy 10% off your first coffee order with code WELCOME10 at checkout.',
    buttonTextTr: 'Taze Hasatları Keşfet (%10 İndirim)',
    buttonTextEn: 'Explore Fresh Harvests (10% Off)',
    buttonText: 'Explore Fresh Harvests (10% Off)',
    buttonUrl: 'https://coffeeesto.com/coffee?coupon=WELCOME10',
    secondaryButtonTextTr: 'Kavurmahane Hikayemizi Oku',
    secondaryButtonTextEn: 'Read Our Roastery Story',
    secondaryButtonText: 'Read Our Roastery Story',
    secondaryButtonUrl: 'https://coffeeesto.com/about',
    footerNoteTr: 'İstanbul’da siparişe özel kavrulan doğrudan ticaret kahveleri.',
    footerNoteEn: 'Direct-trade specialty coffees roasted to order in İstanbul.',
    footerNote: 'Direct-trade specialty coffees roasted to order in İstanbul.',
    enabled: true,
  },
};

export async function GET() {
  try {
    let settings = await db.emailSettings.findUnique({ where: { id: 1 } });
    if (!settings) {
      settings = await db.emailSettings.create({
        data: {
          id: 1,
          provider: 'smtp',
          smtpHost: 'smtp.mailtrap.io',
          smtpPort: 587,
          smtpUser: '',
          smtpPass: '',
          fromEmail: 'orders@grainandgrind.com',
          fromName: 'Coffee Esto Roastery',
          resendApiKey: '',
          templatesJson: JSON.stringify(DEFAULT_EMAIL_TEMPLATES),
        },
      });
    }

    let parsedTemplates = DEFAULT_EMAIL_TEMPLATES;
    try {
      if (settings.templatesJson) {
        parsedTemplates = { ...DEFAULT_EMAIL_TEMPLATES, ...JSON.parse(settings.templatesJson) };
      }
    } catch {}

    return NextResponse.json({
      success: true,
      data: {
        ...settings,
        templates: parsedTemplates,
      },
      error: null,
    });
  } catch (error) {
    console.error('Failed to get email settings:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error retrieving email configuration.' },
      { status: 500 }
    );
  }
}

export async function PUT(request: Request) {
  try {
    const body = await request.json();
    const {
      provider,
      smtpHost,
      smtpPort,
      smtpUser,
      smtpPass,
      fromEmail,
      fromName,
      resendApiKey,
      templates,
    } = body;

    const templatesJson = templates ? JSON.stringify(templates) : undefined;

    const updated = await db.emailSettings.upsert({
      where: { id: 1 },
      create: {
        id: 1,
        provider: provider || 'smtp',
        smtpHost: smtpHost || 'smtp.mailtrap.io',
        smtpPort: Number(smtpPort) || 587,
        smtpUser: smtpUser || '',
        smtpPass: smtpPass || '',
        fromEmail: fromEmail || 'orders@grainandgrind.com',
        fromName: fromName || 'Coffee Esto Roastery',
        resendApiKey: resendApiKey || '',
        templatesJson: templatesJson || JSON.stringify(DEFAULT_EMAIL_TEMPLATES),
      },
      update: {
        provider: provider !== undefined ? provider : undefined,
        smtpHost: smtpHost !== undefined ? smtpHost : undefined,
        smtpPort: smtpPort !== undefined ? Number(smtpPort) : undefined,
        smtpUser: smtpUser !== undefined ? smtpUser : undefined,
        smtpPass: smtpPass !== undefined ? smtpPass : undefined,
        fromEmail: fromEmail !== undefined ? fromEmail : undefined,
        fromName: fromName !== undefined ? fromName : undefined,
        resendApiKey: resendApiKey !== undefined ? resendApiKey : undefined,
        templatesJson: templatesJson !== undefined ? templatesJson : undefined,
      },
    });

    return NextResponse.json({ success: true, data: updated, error: null });
  } catch (error) {
    console.error('Failed to save email settings:', error);
    return NextResponse.json(
      { success: false, error: 'Internal server error saving email configuration.' },
      { status: 500 }
    );
  }
}
