/* eslint-disable @typescript-eslint/no-require-imports */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const defaultCategories = [
  { slug: 'single-origin', label: 'Single Origin' },
  { slug: 'espresso',      label: 'Espresso' },
  { slug: 'filter',        label: 'Filter Coffee' },
  { slug: 'turkish',       label: 'Turkish Coffee' },
  { slug: 'limited-edition', label: 'Limited Edition' },
];

const newProducts = [
  {
    id: 'italian-blend',
    name: 'Italian Blend',
    category: 'espresso',
    origin: 'South America & Asia Blend',
    altitude: '1000m - 1400m',
    varietal: 'Arabica / Robusta Blend',
    roastLevel: 75,
    tastingNotes: 'Strong & Intense',
    description: 'A classic dark Italian roast profile yielding a strong, full-bodied cup with rich chocolate notes and an intense crema.',
    price: 287.50,
    wholesalePrice: 750.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'espresso-gold',
    name: 'Espresso Gold',
    category: 'espresso',
    origin: 'Central & South America',
    altitude: '1200m - 1500m',
    varietal: '100% Arabica',
    roastLevel: 55,
    tastingNotes: 'Balanced & Smooth',
    description: 'Balanced espresso profile with smooth chocolate notes, toasted nuts, and a caramelized sugar sweetness.',
    price: 312.50,
    wholesalePrice: 880.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'premium-blend',
    name: 'Premium Blend',
    category: 'espresso',
    origin: 'Africa & Central America',
    altitude: '1400m - 1800m',
    varietal: '100% Arabica',
    roastLevel: 45,
    tastingNotes: 'Aromatic & Lively',
    description: 'Premium espresso blend displaying lively fruit acidity, complex aromatics, and a sweet floral finish.',
    price: 337.50,
    wholesalePrice: 990.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'velora-signature',
    name: 'Velora Signature Espresso',
    category: 'limited-edition',
    origin: 'Single Estate Micro-Lot',
    altitude: '1800m - 2100m',
    varietal: 'Heirloom Typica',
    roastLevel: 35,
    tastingNotes: 'Floral, Winey, Tropical Fruit, Honey, Bergamot',
    description: 'Exclusive limited edition signature profile with highly complex floral, winey, and tropical fruit notes. 100% Arabica.',
    price: 350.00,
    wholesalePrice: 990.00,
    stock: 50,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/velora-signature.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'house-blend',
    name: 'House Blend',
    category: 'filter',
    origin: 'South American Blend',
    altitude: '1100m - 1300m',
    varietal: '100% Arabica',
    roastLevel: 65,
    tastingNotes: 'Strong & Intense',
    description: 'Classic house filter blend with strong, full-bodied chocolate and toasted hazelnut notes.',
    price: 287.50,
    wholesalePrice: 750.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'special-blend',
    name: 'Special Blend',
    category: 'filter',
    origin: 'Central American Blend',
    altitude: '1300m - 1500m',
    varietal: '100% Arabica',
    roastLevel: 50,
    tastingNotes: 'Balanced & Smooth',
    description: 'A smooth daily filter blend featuring balanced chocolate and sweet caramel notes.',
    price: 325.00,
    wholesalePrice: 880.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'esto-blend',
    name: 'Esto Blend',
    category: 'filter',
    origin: 'African & South American Blend',
    altitude: '1500m - 1700m',
    varietal: '100% Arabica',
    roastLevel: 45,
    tastingNotes: 'Aromatic & Lively',
    description: 'Our signature Esto filter blend with vibrant fruit acidity and aromatic floral finish.',
    price: 337.50,
    wholesalePrice: 990.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'colombia',
    name: 'Colombia Supremo',
    category: 'single-origin',
    origin: 'Huila, Colombia',
    altitude: '1600m - 1800m',
    varietal: 'Caturra',
    roastLevel: 55,
    tastingNotes: 'Chocolate, Hazelnut, Caramel',
    description: 'Supremo grade single origin from Colombia offering classic sweet chocolate, rich hazelnut, and caramel notes.',
    price: 350.00,
    wholesalePrice: 1220.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/colombia.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'guatemala',
    name: 'Guatemala',
    category: 'single-origin',
    origin: 'Antigua, Guatemala',
    altitude: '1500m - 1700m',
    varietal: 'Bourbon, Caturra',
    roastLevel: 50,
    tastingNotes: 'Chocolate, Orange, Sweet Acidity',
    description: 'Grown in high-altitude volcanic soils, this Guatemalan origin delivers rich cocoa and sweet citrus orange finish.',
    price: 337.50,
    wholesalePrice: 1220.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/guatemala.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'kenya',
    name: 'Kenya',
    category: 'single-origin',
    origin: 'Nyeri, Kenya',
    altitude: '1700m - 1900m',
    varietal: 'SL28, SL34',
    roastLevel: 40,
    tastingNotes: 'Dark Fruit, Grape, Floral',
    description: 'Distinctive Kenyan profile with intense dark currant notes, juicy grape acidity, and a clean floral body.',
    price: 350.00,
    wholesalePrice: 1190.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/kenya.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'ethiopia',
    name: 'Etiyopya Sidamo',
    category: 'single-origin',
    origin: 'Sidamo, Ethiopia',
    altitude: '1800m - 2000m',
    varietal: 'Heirloom Typica',
    roastLevel: 35,
    tastingNotes: 'Bergamot, Citrus, Tea Notes',
    description: 'Traditional washed Sidamo profile displaying sweet bergamot, lemon-lime citrus, and a black tea-like body.',
    price: 325.00,
    wholesalePrice: 1190.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/ethiopia-sidamo.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'brazil-cerrado',
    name: 'Brezilya Cerrado',
    category: 'single-origin',
    origin: 'Cerrado, Brazil',
    altitude: '900m - 1100m',
    varietal: 'Mundo Novo',
    roastLevel: 60,
    tastingNotes: 'Chocolate, Hazelnut, Low Acidity',
    description: 'Classic natural processed Cerrado crop. Very low in acidity with rich creamy chocolate and toasted hazelnut notes.',
    price: 312.50,
    wholesalePrice: 990.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/brazil-cerrado.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'brazil-mogiana',
    name: 'Brezilya Mogiana',
    category: 'single-origin',
    origin: 'Alta Mogiana, Brazil',
    altitude: '1000m - 1200m',
    varietal: 'Mundo Novo, Catuai',
    roastLevel: 55,
    tastingNotes: 'Caramel, Hazelnut, Balanced',
    description: 'Sweet, balanced Mogiana origin highlighting toasted nuts, light citrus brightness, and a caramel finish.',
    price: 325.00,
    wholesalePrice: 1170.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/brazil-mogiana.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'brazil-rio-minas',
    name: 'Brezilya Rio Minas',
    category: 'single-origin',
    origin: 'Minas Gerais, Brazil',
    altitude: '800m - 1000m',
    varietal: 'Catuai',
    roastLevel: 60,
    tastingNotes: 'Chocolate, Light Body',
    description: 'Traditional Brazilian cup, light in body and sweet in finish, with subtle cocoa notes.',
    price: 287.50,
    wholesalePrice: 880.00,
    stock: 100,
    imageUrl: 'https://fdoukqqdqllistvqxvtu.supabase.co/storage/v1/object/public/product-media/images/coffee_packs/brazil-rio-minas.webp',
    videoUrl: '',
    isActive: true,
  },
  {
    id: 'turk-kahvesi',
    name: 'Türk Kahvesi',
    category: 'turkish',
    origin: 'Brazil & Colombia Blend',
    altitude: '1000m - 1600m',
    varietal: 'Arabica',
    roastLevel: 60,
    tastingNotes: 'Rio Minas + Colombia, Fine Grind',
    description: 'Finely ground traditional Turkish coffee blend of Rio Minas and Colombian crops for a thick, rich crema.',
    price: 287.50,
    wholesalePrice: 780.00,
    stock: 100,
    imageUrl: '',
    videoUrl: '',
    isActive: true,
  },
];

async function main() {
  console.log('Seeding categories...');
  for (const cat of defaultCategories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { label: cat.label },
      create: cat,
    });
  }

  console.log('Seeding products...');
  for (const product of newProducts) {
    await prisma.product.upsert({
      where: { id: product.id },
      update: product,
      create: product,
    });
  }

  // Clean up old products not in the new price list
  const newProductIds = newProducts.map(p => p.id);
  const deleted = await prisma.product.deleteMany({
    where: {
      id: { notIn: newProductIds }
    }
  });
  console.log(`Cleaned up ${deleted.count} old products.`);

  console.log('Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
